name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      tomcat:
        image: tomcat:10.1-jdk17
        ports:
          - 8080:8080
        options: --health-cmd "curl -f http://localhost:8080/ || exit 1" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build and test
      run: mvn -B clean package
      
    - name: Deploy to Tomcat
      run: |
        WAR_FILE=$(ls target/*.war | head -1)
        docker exec tomcat mkdir -p /usr/local/tomcat/webapps
        docker cp $WAR_FILE tomcat:/usr/local/tomcat/webapps/
        docker exec tomcat catalina.sh start
      if: github.ref == 'refs/heads/master'
      
    - name: Verify deployment
      run: |
        sleep 10  # Attente du démarrage de Tomcat
        docker exec tomcat curl --retry 5 --retry-delay 10 --retry-connrefused http://localhost:8080/manager/text/list
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: target/surefire-reports