name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build and test
      run: mvn -B clean package
      
    - name: Start Tomcat
      run: |
        docker run -d --name tomcat -p 8080:8080 tomcat:10.1-jdk17
        sleep 10  # Attendre que Tomcat démarre
        
    - name: Deploy to Tomcat
      run: |
        WAR_FILE=$(ls target/*.war | head -1)
        docker cp $WAR_FILE tomcat:/usr/local/tomcat/webapps/
        docker exec tomcat catalina.sh start
        sleep 5  # Attendre que l'application se déploie
        
    - name: Verify deployment
      run: |
        curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:8080/manager/text/list
        
    - name: Upload test results
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/surefire-reports